### ISSUE TITLE
'function' has no attribute 'get'

### ISSUE THREAD

**Issue by ghost** [insynchq/flask-googlelogin#19]
I've been using the extension for some time now. But now I've created a new example based on the one here, and I get the following error:
Warning:
flask_googlelogin/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning

Error:
Traceback (most recent call last):
  File "/home/amin/flask_googlelogin/lib/python2.7/site-packages/flask/app.py", line 1836, in **call**
    return self.wsgi_app(environ, start_response)
  File "/home/amin/flask_googlelogin/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/amin/flask_googlelogin/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/amin/flask_googlelogin/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/amin/flask_googlelogin/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/amin/flask_googlelogin/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/amin/flask_googlelogin/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/amin/flask_googlelogin/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/amin/flask_googlelogin/lib/python2.7/site-packages/flask_googlelogin.py", line 198, in decorated
    _scheme=self.redirect_scheme,
  File "/home/amin/flask_googlelogin/lib/python2.7/site-packages/flask_googlelogin.py", line 144, in exchange_code
    if not token or token.get('error'):
AttributeError: 'function' object has no attribute 'get'

**Comment by ghost** [comment]
Updating the Flask-GoogleLogin solved the problem.
