### ISSUE TITLE
Requests library compatibility issue with chardet2

### ISSUE THREAD

**Issue by vsoch** [insynchq/flask-googlelogin#21]
Any plans to update this library? I can't even install it, and I think it's a dependency compatability issue (requests and compat2?)

```bash
  Using cached https://files.pythonhosted.org/packages/fa/d1/0dd60e1146e79e7b193e7b0189d8c13ef100d55cbfe65e1825ac5f03c397/requests-0.14.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-n9u2f5pi/requests/setup.py", line 6, in <module>
        import requests
      File "/tmp/pip-install-n9u2f5pi/requests/requests/__init__.py", line 52, in <module>
        from . import utils
      File "/tmp/pip-install-n9u2f5pi/requests/requests/utils.py", line 22, in <module>
        from .compat import parse_http_list as _parse_list_header
      File "/tmp/pip-install-n9u2f5pi/requests/requests/compat.py", line 112, in <module>
        from .packages import chardet2 as chardet
    ImportError: cannot import name 'chardet2'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-n9u2f5pi/requests/
```

**Comment by bugsduggan** [comment]
This project appears to no longer be maintained. The readme points to [flask-oauth2-login](https://github.com/marksteve/flask-oauth2-login), you might have more luck with that.
